### ISSUE TITLE
library not found for -lPods-TempoDisc

### ISSUE THREAD

**Issue by dotdreaming** [BlueMaestro/IOS-Tempo-Utility-App-SDK#1]
ld: library not found for -lPods-TempoDisc
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am getting the above  error on build in xcode 8.
I "Pod installed' first then opened the Tempo Utility.xcworkspace file and tried building this and got the above error.

Any way I can get his running?

Many thanks

**Comment by dotdreaming** [comment]
I have downloaded the latest version of the SDK and still getting this discrepancy against the TempDisc name.  The error in the screenshot is given after I initially run 'Pod Install' and open the 'Tempo Utility.xcworkspace' file and run a build.
![screen shot 2016-10-31 at 17 16 04](https://cloud.githubusercontent.com/assets/808135/19864036/7103ea76-9f8e-11e6-9b45-110086fdf0d7.png)

**Comment by BlueMaestro** [comment]
Hi Brian, yes this was a reference to the old app that had a different name.  Deleting the references to TempoDisc fixes this, but anyway the latest commits has fixed this for good.
