### ISSUE TITLE
[!] Unable to find a target named `TempoDisc`, did find `Tempo Utility`.

### ISSUE THREAD

**Issue by dotdreaming** [BlueMaestro/IOS-Tempo-Utility-App-SDK#2]
I had an issue running the Pod Install command when downloading the latest SDK update. The Target inside the Podfile is pointing to the incorrect name.

To get the Pod Install to install the dependencies I had to change line number 6 from "target 'TempoDisc' do" to:
`target 'Tempo Utility' do`

![screen shot 2016-10-31 at 17 10 45](https://cloud.githubusercontent.com/assets/808135/19864214/2a7617b8-9f8f-11e6-982c-a3bc37709bdc.png)

Many thanks
Brian

**Comment by BlueMaestro** [comment]
Thanks Brian, yes this was an incorrect reference to the old version of the app that had a different name.  Changing the reference target to Tempo Utility from Tempo Disc solved this, but the latest commit has fixed this in any respect
